# Modelling Classical, probabilistic, and Quantum Systems

## Classical Discrete Systems
![Deterministic System](images/ClassicPhysicalSystem.png)



Modeling the dynamic behaviors and the state of a classical discrete system using matrices and vectors. The state after one click is computed as follows:

$$
    \begin{bmatrix} 0 && 0 && 0 && 0 && 0 && 0 \\
                   0 && 0 && 0 && 0 && 0 && 0 \\
                   0 && 1 && 0 && 0 && 0 && 1 \\
                   0 && 0 && 0 && 1 && 0 && 0 \\
                   0 && 0 && 1 && 0 && 0 && 0 \\
                   1 && 0 && 0 && 0 && 1 && 0 \\
    \end{bmatrix}
    \begin{bmatrix} 6 \\
                    2 \\
                    1 \\
                    5 \\
                    3 \\
                    10 \\
    \end{bmatrix}
    =
    \begin{bmatrix} 0 \\
                    0 \\
                    12 \\
                    5 \\
                    1 \\
                    9 \\
    \end{bmatrix}$$

In [1]:
import numpy as np

# Define two 3x3 complex matrices
m1 = np.array([[0,0,0,0,0,0],
               [0,0,0,0,0,0],
               [0,1,0,0,0,1],
               [0,0,0,1,0,0],
               [0,0,1,0,0,0],
               [1,0,0,0,1,0]])

v1 = np.array([[6], [2], [1], [5], [3], [10]])


print("Input: ", m1,v1)

# Multiplying a 3x3 matrix by a 3x1 vector
state_after_one_click = np.dot(m1, v1)
print("Result after one Click: ", state_after_one_click)

Input:  [[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 1]
 [0 0 0 1 0 0]
 [0 0 1 0 0 0]
 [1 0 0 0 1 0]] [[ 6]
 [ 2]
 [ 1]
 [ 5]
 [ 3]
 [10]]
Result after one Click:  [[ 0]
 [ 0]
 [12]
 [ 5]
 [ 1]
 [ 9]]


![State after two clicks.](images/ClassicPhysicalSystem2.png)

The state after two cliks is computed as follows:

In [2]:
print("Result after two clicks: ", np.dot(m1,state_after_one_click))

Result after two clicks:  [[ 0]
 [ 0]
 [ 9]
 [ 5]
 [12]
 [ 1]]


## Exercises



### Excercise 1:

1. Write a program to model the behavior of the probabilistic double slit example depicted in the figure.
2. Show the results of the experiment using a bar diagram. Each bar represents the intensity of the light at the specific target.


![Probabilistic Double slit.](images/ProbabilisticSystem.png)

In [3]:
import numpy as np

# Número de estados
n = 6

# Matriz de transición determinista (permuta circular)
M = np.zeros((n, n), dtype=int)
for i in range(n):
    M[i, (i+1) % n] = 1

print("Matriz de transición:\n", M)

# Estado inicial
s0 = np.zeros(n)
s0[0] = 1
print("\nEstado inicial:\n", s0)

# Estado después de 1 click
s1 = s0 @ M
print("\nEstado tras 1 click:\n", s1)

# Estado después de 2 clicks
s2 = s1 @ M
print("\nEstado tras 2 clicks:\n", s2)


Matriz de transición:
 [[0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [1 0 0 0 0 0]]

Estado inicial:
 [1. 0. 0. 0. 0. 0.]

Estado tras 1 click:
 [0. 1. 0. 0. 0. 0.]

Estado tras 2 clicks:
 [0. 0. 1. 0. 0. 0.]


### Excercise 2:

1. Write a program to model the behavior of the quantum double slit example depicted in the figure.
2. Show the results of the experiment using a bar diagram. Each bar represents the intensity of the light at the specific target.


![Probabilistic Double slit.](images/QuantumSystem.png)

In [4]:
import numpy as np

# Matriz de transición (ejemplo válida)
P = np.array([[0.9, 0.1],
              [0.5, 0.5]])

print("Matriz de transición:\n", P)
print("Suma por filas (debe ser 1):", P.sum(axis=1))

# Distribución inicial
pi0 = np.array([1, 0])

# Evolución
pi1 = pi0 @ P
pi2 = pi1 @ P
pi10 = pi0 @ np.linalg.matrix_power(P, 10)

print("\nEstado inicial:", pi0)
print("Después de 1 paso:", pi1)
print("Después de 2 pasos:", pi2)
print("Después de 10 pasos:", pi10)


Matriz de transición:
 [[0.9 0.1]
 [0.5 0.5]]
Suma por filas (debe ser 1): [1. 1.]

Estado inicial: [1 0]
Después de 1 paso: [0.9 0.1]
Después de 2 pasos: [0.86 0.14]
Después de 10 pasos: [0.83335081 0.16664919]
